### PR TITLE
added full node

### PR DESCRIPTION
**Pull request by interbiznw**
added full node to nodes list

### CODE REVIEW

**Comment by interbiznw** [comment]
added some nodes i spun up in North america, London, and Singapore

**Comment by interbiznw** [comment]
removed rpcport

**Comment by 11000000110000110100001101011010** [comment]
There will be support for a long time on your nodes ?

**Comment by interbiznw** [comment]
Yes they will be up long term no problem. I have lots of resources, These are no issue running for a long time.

**Pull request merged**
